### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by shmuelbarkin** [meyerauslander/My-Zmanim-Wordpress-Widget#11]
When the plugin is activated, the user gets the following error `The plugin does not have a valid header.`

Screenshot:
<img width="804" alt="2018-05-02_1034" src="https://user-images.githubusercontent.com/22505270/39529424-a8a9fd1a-4df4-11e8-8011-e209ba576445.png">

**Comment by meyerauslander** [comment]
I know about this issue but I'm not sure if there is any acceptable way to fix it.  Anyway, it isn't a real problem, you can still proceed to active and use this plugin normally.  Just ignore this error message.  Thanks for your input...

**Comment by meyerauslander** [comment]
I found  a possible solution to this problem!  Clear out the WP cache and then reinstall the plugin.  One easy way of clearing the cache is with the 'wp-super-cache' plugin.  https://wordpress.org/plugins/wp-super-cache/.  Simply install it and then go to the it's settings page in the admin.  Click on the button that says "Delete Cache".  Now you should no longer get the "invalid header" error!
